"""Evaluation pipeline for embedding-only, geometry-only, and hybrid models.

Inputs expect the embedding dataset structure generated by src/feature_extraction.py:
<emb_dir>/<person>/<sample>.npy and optional <sample>.geo.npy
"""

import argparse
import csv
import os
from dataclasses import dataclass
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


@dataclass
class EvalResult:
    model: str
    accuracy: float
    precision: float
    recall: float


def load_feature_dataset(emb_dir: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict[int, str]]:
    emb_list: List[np.ndarray] = []
    geo_list: List[np.ndarray] = []
    y_list: List[int] = []
    idx2label: Dict[int, str] = {}

    label_idx = 0
    for person in sorted(os.listdir(emb_dir)):
        person_dir = os.path.join(emb_dir, person)
        if not os.path.isdir(person_dir):
            continue
        idx2label[label_idx] = person

        for file_name in sorted(os.listdir(person_dir)):
            if not file_name.endswith('.npy') or file_name.endswith('.geo.npy'):
                continue
            emb_path = os.path.join(person_dir, file_name)
            geo_path = emb_path.replace('.npy', '.geo.npy')

            emb = np.load(emb_path).astype(np.float32).reshape(-1)
            geo = np.load(geo_path).astype(np.float32).reshape(-1) if os.path.exists(geo_path) else np.zeros(12, dtype=np.float32)

            emb_list.append(emb)
            geo_list.append(geo)
            y_list.append(label_idx)

        label_idx += 1

    if not emb_list:
        raise ValueError(f"No embedding samples found in {emb_dir}")

    return np.vstack(emb_list), np.vstack(geo_list), np.array(y_list, dtype=np.int64), idx2label


def split_data(emb: np.ndarray, geo: np.ndarray, y: np.ndarray, test_size: float, random_state: int):
    stratify = y if len(np.unique(y)) > 1 and np.min(np.bincount(y)) > 1 else None
    return train_test_split(
        emb,
        geo,
        y,
        test_size=test_size,
        random_state=random_state,
        stratify=stratify,
    )


def fit_and_evaluate(name: str, x_train: np.ndarray, x_test: np.ndarray, y_train: np.ndarray, y_test: np.ndarray) -> EvalResult:
    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    clf = LogisticRegression(max_iter=2000)
    clf.fit(x_train_scaled, y_train)
    y_pred = clf.predict(x_test_scaled)

    return EvalResult(
        model=name,
        accuracy=accuracy_score(y_test, y_pred),
        precision=precision_score(y_test, y_pred, average='macro', zero_division=0),
        recall=recall_score(y_test, y_pred, average='macro', zero_division=0),
    )


def save_csv(results: List[EvalResult], out_csv: str):
    os.makedirs(os.path.dirname(out_csv) or '.', exist_ok=True)
    with open(out_csv, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['model', 'accuracy', 'precision_macro', 'recall_macro'])
        for r in results:
            writer.writerow([r.model, f"{r.accuracy:.6f}", f"{r.precision:.6f}", f"{r.recall:.6f}"])


def save_plot(results: List[EvalResult], out_plot: str):
    os.makedirs(os.path.dirname(out_plot) or '.', exist_ok=True)
    names = [r.model for r in results]
    acc = [r.accuracy for r in results]
    prec = [r.precision for r in results]
    rec = [r.recall for r in results]

    x = np.arange(len(names))
    width = 0.25

    plt.figure(figsize=(9, 5))
    plt.bar(x - width, acc, width, label='Accuracy')
    plt.bar(x, prec, width, label='Precision (macro)')
    plt.bar(x + width, rec, width, label='Recall (macro)')
    plt.xticks(x, names)
    plt.ylim(0, 1)
    plt.ylabel('Score')
    plt.title('Model Comparison: Embedding vs Geometry vs Hybrid')
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_plot, dpi=150)


def main():
    parser = argparse.ArgumentParser(description='Evaluate embedding-only, geometry-only, and hybrid models.')
    parser.add_argument('--emb_dir', default='data/embeddings', help='Directory containing .npy and .geo.npy files by class.')
    parser.add_argument('--test_size', type=float, default=0.2)
    parser.add_argument('--random_state', type=int, default=42)
    parser.add_argument('--out_csv', default='artifacts/evaluation_results.csv')
    parser.add_argument('--out_plot', default='artifacts/evaluation_comparison.png')
    args = parser.parse_args()

    emb, geo, y, _ = load_feature_dataset(args.emb_dir)
    emb_train, emb_test, geo_train, geo_test, y_train, y_test = split_data(emb, geo, y, args.test_size, args.random_state)

    hybrid_train = np.concatenate([emb_train, geo_train], axis=1)
    hybrid_test = np.concatenate([emb_test, geo_test], axis=1)

    results = [
        fit_and_evaluate('embedding_only', emb_train, emb_test, y_train, y_test),
        fit_and_evaluate('geometry_only', geo_train, geo_test, y_train, y_test),
        fit_and_evaluate('hybrid', hybrid_train, hybrid_test, y_train, y_test),
    ]

    save_csv(results, args.out_csv)
    save_plot(results, args.out_plot)

    for r in results:
        print(f"{r.model}: accuracy={r.accuracy:.4f}, precision={r.precision:.4f}, recall={r.recall:.4f}")
    print(f"CSV saved to: {args.out_csv}")
    print(f"Plot saved to: {args.out_plot}")


if __name__ == '__main__':
    main()
